ekonomi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [ # pylint: disable=C0103
    path('', views.ExpenseSummary.as_view(), name='root'),
    path('expense', views.ExpenseIndex.as_view(), name='expense-list'),
    path('expense/add', views.ExpenseCreate.as_view(), name='expense-create'),
    path('expense/<int:pk>/', views.ExpenseUpdate.as_view(), name='expense-update'),
    path('expense/<int:pk>/delete', views.ExpenseDelete.as_view(), name='expense-delete'),
    path('upload', views.UploadIndex.as_view(), name='upload-list'),
    path('upload/add', views.UploadCreate.as_view(), name='upload-create'),
    path('upload/<int:pk>/', views.UploadUpdate.as_view(), name='upload-update'),
    path('upload/<int:pk>/delete', views.UploadDelete.as_view(), name='upload-delete'),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ekonomi/models.py
"""
Defines applications database models
"""

import csv
import re
from datetime import datetime
from decimal import Decimal
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

class Expense(models.Model):
    title = models.CharField(max_length=200)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_date = models.DateField('date payed')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {} kr, {:%Y-%m-%d}".format(self.title, self.amount, self.transaction_date)


    def get_absolute_url(self):
        return reverse('expense-update', kwargs={'pk': self.pk})


class Upload(models.Model):
    ICA_CSV = 0
    KIND_CHOICES = (
        (ICA_CSV, _('ica_csv')),
    )
    file = models.FileField()
    kind = models.IntegerField(choices=KIND_CHOICES, default=ICA_CSV, verbose_name=_('Kind'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('upload-update', kwargs={'pk': self.pk})

    def expenses(self):
        expenses = []
        with self.file.open(mode='r') as file:
            reader = csv.DictReader(file, delimiter=';')
            for row in reader:
                if row["Typ"] in ['Korttransaktion', 'Autogiro']:
                    expense, _ = Expense.objects.get_or_create(title=row["Text"],
                                                                     amount=self._to_decimal(row["Belopp"]),
                                                                     transaction_date=self._parse_date(row["\ufeffDatum"]))
                    expenses.append(expense)
        return expenses

    @staticmethod
    def _to_decimal(string):
        string = re.sub(r',', ".", string)
        string = re.sub(r' |kr', "", string)
        return -1 * Decimal(string)


    @staticmethod
    def _parse_date(string):
        return datetime.strptime(string, '%Y-%m-%d').date()

ekonomi/forms.py
"""
Defines all form objects in the application
"""

from django import forms

ekonomi/views.py
"""
View-objects in application
"""

from django.db.models import Sum
from django.db.models.functions import ExtractMonth, ExtractYear
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView

from .models import Expense, Upload

class ExpenseSummary(ListView):
    template_name = 'ekonomi/expense_summary.html'
    model = Expense


    def get_queryset(self):
        expenses = Expense.objects \
                          .order_by('-transaction_date') \
                          .annotate(month=ExtractMonth('transaction_date'),
                                    year=ExtractYear('transaction_date')) \
                          .values('month', 'year') \
                          .annotate(sum=Sum('amount')) \
                          .order_by()
        return expenses


class ExpenseIndex(ListView):
    model = Expense
    def get_queryset(self):
        """Return the last five published questions."""
        return Expense.objects.order_by('-transaction_date')

    def get_context_data(self, **kwargs):
        context = super(ExpenseIndex, self).get_context_data(**kwargs)
        context['sum'] = context['expense_list'].aggregate(Sum('amount'))['amount__sum']
        return context


class ExpenseCreate(CreateView):
    model = Expense
    fields = ['title', 'amount', 'transaction_date']


class ExpenseUpdate(UpdateView):
    model = Expense
    fields = ['title', 'amount', 'transaction_date']


class ExpenseDelete(DeleteView):
    model = Expense
    success_url = reverse_lazy('expense-list')


class UploadCreate(CreateView):
    model = Upload
    fields = ['file', 'kind']

    def post(self, request, *args, **kwargs):
        print('POST')
        print(request.POST)
        print(request.FILES)
        return super(UploadCreate, self).post(request, *args, **kwargs)


class UploadUpdate(UpdateView):
    model = Upload
    fields = ['file', 'kind']


class UploadIndex(ListView):
    def get_queryset(self):
        """Return the last five published questions."""
        return Upload.objects.all()


class UploadDelete(DeleteView):
    model = Upload
    success_url = reverse_lazy('upload-list')

ekonomi/templates/ekonomi/base.html
{% load static %}
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ekonomi</title>
    <link rel="stylesheet" href="{% static 'ekonomi/style.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
  </head>
  <body class="flex flex-col min-h-screen bg-blue-lightest" style="min-height: 100vh">
    <header>
        {% include 'ekonomi/header.html' %}
    </header>

    <main class="flex flex-1 justify-center mx-auto w-full border-t-2 border-blue-lighter">
        <div class="w-full md:w-1/5 mt-4">
            {% include 'ekonomi/sidebar.html' %}
        </div>
        <div class="w-full md:w-3/5 mt-4">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <footer>
        {% block footer %}
        {% endblock %}
    </footer>
  </body>
</html>

ekonomi/templates/ekonomi/expense_confirm_delete.html
{% extends 'expenses/base.html' %}

{% block content %}
<h2>
    {{ expense }}
</h2>

<form action="" method="post" class="mt-auto">
    {% csrf_token %}
    <input class="p-2 bg-white text-blue hover:bg-grey hover:text-white rounded" name="delete" type="submit" value="Ta bort"/>
</form>
{% endblock %}

ekonomi/templates/ekonomi/expense_form.html
{% extends 'ekonomi/base.html' %}

{% block content %}
<h2>
    Utgift
</h2>

<div class="flex justify-between ">
    <form method="post" class="w-full pt-3" novalidate>
        {% csrf_token %}
        {{ form.non_field_errors }}

        {{ form.source.errors }}
        {{ form.source }}
        <div class="mb-4">
            <div class="block text-grey-darker text-sm font-bold mb-2">
                {{ form.title.label_tag }}
            </div>
            {{ form.title }}
        </div>
        <div class="mb-4">
            <div class="block text-grey-darker text-sm font-bold mb-2">
                {{ form.amount.label_tag }}
            </div>
            {{ form.amount }}
        </div>
        <div class="mb-4">
            <div class="block text-grey-darker text-sm font-bold mb-2">
                {{ form.transaction_date.label_tag }}
            </div>
            {{ form.transaction_date }}
        </div>
        <input type="submit" value="Save" class="p-2 bg-blue text-white hover:bg-blue-dark rounded">
    </form>
    {% if expense.id %}
        <div class="mt-auto">
            <a href="{% url 'expense-delete' expense.id %}" class="p-2 bg-white text-blue hover:bg-grey hover:text-white rounded">
                Ta bort
            </a>
        </div>
    {% endif %}
</div>
{% if expense.id %}
    <div class="mt-auto">
        <a href="{% url 'expense-delete' expense.id %}" class="p-2 bg-white text-blue hover:bg-grey hover:text-white rounded">
            Ta bort
        </a>
    </div>
{% endif %}
{% endblock %}

ekonomi/templates/ekonomi/expense_list.html
{% extends 'ekonomi/base.html' %}

{% block title %}
    <h1>Expenses</h1>
{% endblock %}

{% block content %}
    <div class="">
        <h2>Utlägg</h2>
    </div>
    <div class="pt-4">
        {% include "ekonomi/expense_table.html" with expense_list=expense_list sum=sum %}
        <div class="mt-6">
            <a href="{% url 'expense-create' %}"
               class="p-2 bg-white text-blue hover:bg-grey hover:text-white rounded">
                Lägg till utgift
            </a>
        </div>
    </div>
{% endblock %}

ekonomi/templates/ekonomi/expense_summary.html
{% extends 'ekonomi/base.html' %}

{% block title %}
    <h1>Expenses</h1>
{% endblock %}

{% block content %}
    <div class="">
        <h2>Utlägg</h2>
    </div>
    <div class="pt-4">
        <table class="table-auto w-full border-black">
            <thead class="bg-blue text-white text-left">
                <tr class="border-b">
                    <th class="p-2" scope="col">Månad</th>
                    <th class="p-2" scope="col">Summa</th>
                </tr>
            </thead>
            <tbody>
                {% for row in expense_list %}
                    <tr class="border-black border-b border-l">
                        <td class="border-black border-r p-2">{{ row.year }}-{{ row.month|stringformat:"02d" }}</td>
                        <td class="border-black border-r p-2">{{ row.sum|floatformat:1 }} kr</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

ekonomi/templates/ekonomi/expense_table.html
<table class="table-auto w-full border-black">
    <thead class="bg-blue text-white text-left">
        <tr class="border-b">
            <th class="p-2" scope="col">Titel</th>
            <th class="p-2" scope="col">Datum</th>
            <th class="p-2" scope="col">Belopp</th>
        </tr>
    </thead>
    <tbody>
        {% for expense in expense_list %}
            <tr class="border-black border-b border-l">
                <td class="border-black border-r p-2">
                    {% if expense.id %}
                        <a href="{% url 'expense-update' expense.id %}">{{ expense.title }}</a>
                    {% else %}
                        {{ expense.title }}
                    {% endif %}
                </td>
                <td class="border-black border-r p-2">{{ expense.transaction_date }}</td>
                <td class="border-black border-r p-2">{{ expense.amount }} kr</td>
            </tr>
        {% endfor %}
        <tr class="border-black border-b border-l">
            <td></td>
            <td></td>
            <td class="border-black border-r p-2">{{ sum }} kr</td>
        </tr>
    </tbody>
</table>

ekonomi/templates/ekonomi/header.html
<!--Logo & name-->
<nav class="flex items-center justify-between flex-wrap bg-white p-6 border-b-1">
    <div class="flex items-center flex-no-shrink mr-6">
        <span class="font-semibold text-3xl text-blue tracking-light mr-6">
            Ekonomi
        </span>
    </div>

    <!-- Menu -->
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-teal-lighter tw-button button-teal-inverse" id="menu-button" data-state="open">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <title>Menu</title>
                <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
            </svg>
        </button>
    </div>
    <div id="menu-content" class="w-full block flex-grow lg:flex lg:items-center lg:w-auto text-lg border-t lg:border-0 mt-2 lg:mt-0">
        <div class="lg:flex-grow">
        </div>
        <div>
        </div>
    </div>
</nav>

ekonomi/templates/ekonomi/sidebar.html
<div class="px-4 text-center text-grey-lighter">
    <div class="w-full mb-6 text-center text-black">
        <h3>Välkommen</h3><br>
        <h4>{{ 'David Wessman' }}</h4>
    </div>
    <div class="w-full text-center mt-8">
        <ul class="list-reset">
            <li class="">
                <a href="{% url 'root' %}"
                   class="inline-block border-t w-full py-4 font-semibold text-blue no-underline">
                    Startsida
                </a>
            </li>
            <li class="">
                <a href="{% url 'expense-list' %}"
                   class="inline-block border-t w-full py-4 font-semibold text-blue no-underline">
                    Utlägg
                </a>
            </li>
            <li class="">
                <a href="{% url 'upload-list' %}"
                   class="inline-block border-t w-full py-4 font-semibold text-blue no-underline">
                    Uppladdningar
                </a>
            </li>
        </ul>
    </div>
</div> 

ekonomi/templates/ekonomi/upload_confirm_delete.html
{% extends 'ekonomi/base.html' %}

{% block content %}
<h2>
    {{ expense }}
</h2>

<form action="" method="post" class="mt-auto">
    {% csrf_token %}
    <input class="p-2 bg-white text-blue hover:bg-grey hover:text-white rounded" name="delete" type="submit" value="Ta bort"/>
</form>
{% endblock %}

ekonomi/templates/ekonomi/upload_form.html
{% extends 'ekonomi/base.html' %}

{% block content %}
<h2>
    Filer med utlägg
</h2>

<div class="flex justify-between">
    <form method="post" enctype="multipart/form-data" class="w-full pt-3">
        {% csrf_token %}
        {{ form.non_field_errors }}

        {{ form.source.errors }}
        {{ form.source }}
        <div class="mb-4">
            <div class="block text-grey-darker text-sm font-bold mb-2">
                {{ form.kind.label_tag }}
            </div>
            {{ form.kind.errors }}
            {{ form.kind }}
        </div>
        <div class="mb-4">
            <div class="block text-grey-darker text-sm font-bold mb-2">
                {{ form.file.label_tag }}
            </div>
            {{ form.file.errors }}
            {{ form.file }}
        </div>
        <input type="submit" value="Save" class="p-2 bg-blue text-white hover:bg-blue-dark rounded">
    </form>
    {% if upload.id %}
        <div class="mt-auto">
            <a href="{% url 'upload-delete' upload.id %}" class="p-2 bg-white text-blue hover:bg-grey hover:text-white rounded">
                Ta bort
            </a>
        </div>
    {% endif %}
</div>
{% if upload.id %}
    <div class="pt-3">
        <h3>Utlägg</h3>
        <div class="pt-3">
            {% include "ekonomi/expense_table.html" with expense_list=upload.expenses %}
        </div>
    </div>
{% endif %}
{% endblock %}

ekonomi/templates/ekonomi/upload_list.html
{% extends 'ekonomi/base.html' %}

{% block content %}
    <div class="">
        <h2>Uppladdningar</h2>
    </div>
    <div class="p-4">
        <table class="table-auto w-full border-black">
            <thead class="bg-blue text-white text-left">
                <tr class="border-b">
                    <th class="p-2" scope="col">Fil</th>
                    <th class="p-2" scope="col">Typ</th>
                </tr>
            </thead>
            <tbody>
                {% for upload in upload_list %}
                    <tr class="border-black border-b border-l">
                        <td class="border-black border-r p-2">
                            <a href="{% url 'upload-update' upload.id %}">{{ upload.file }}</a>
                        </td>
                        <td class="border-black border-r p-2">{{ upload.get_kind_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="mt-6">
            <a href="{% url 'upload-create' %}"
               class="p-2 bg-white text-blue hover:bg-grey hover:text-white rounded">
                Ladda upp ny fil
            </a>
        </div>
    </div>
{% endblock %}

ekonomi/templates/expenses/base.html
{% load static %}
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ekonomi</title>
    <link rel="stylesheet" href="{% static 'ekonomi/style.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
  </head>
  <body class="flex flex-col min-h-screen bg-blue-lightest" style="min-height: 100vh">
    <header>
        {% include 'expenses/header.html' %}
    </header>

    <main class="flex flex-1 justify-center mx-auto w-full border-t-2 border-blue-lighter">
        <div class="w-full md:w-1/5 mt-4">
            {% include 'expenses/sidebar.html' %}
        </div>
        <div class="w-full md:w-3/5 mt-4">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <footer>
        {% block footer %}
        {% endblock %}
    </footer>
  </body>
</html>

ekonomi/templates/expenses/header.html
<!--Logo & name-->
<nav class="flex items-center justify-between flex-wrap bg-white p-6 border-b-1">
    <div class="flex items-center flex-no-shrink mr-6">
        <span class="font-semibold text-3xl text-blue tracking-light mr-6">
            Ekonomi
        </span>
    </div>

    <!-- Menu -->
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-teal-lighter tw-button button-teal-inverse" id="menu-button" data-state="open">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <title>Menu</title>
                <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
            </svg>
        </button>
    </div>
    <div id="menu-content" class="w-full block flex-grow lg:flex lg:items-center lg:w-auto text-lg border-t lg:border-0 mt-2 lg:mt-0">
        <div class="lg:flex-grow">
        </div>
        <div>
            <a href="">
                Test
            </a>
        </div>
    </div>
</nav>

ekonomi/templates/expenses/index.html
{% extends 'expenses/base.html' %}

{% block title %}
    <h1>Expenses</h1>
{% endblock %}

{% block content %}
    <div class="">
        <h2>Utlägg</h2>
    </div>
    <div class="p-4">
        <table class="table-auto w-full border-black">
            <thead class="bg-blue text-white text-left">
                <tr class="border-b">
                    <th class="p-2" scope="col">Titel</th>
                    <th class="p-2" scope="col">Belopp</th>
                    <th class="p-2" scope="col">Datum</th>
                </tr>
            </thead>
            <tbody>
                {% for expense in expense_list %}
                    <tr class="border-black border-b border-l">
                        <td class="border-black border-r p-2">
                            <a href="{% url 'expense-update' expense.id %}">{{ expense.title }}</a>
                        </td>
                        <td class="border-black border-r p-2">{{ expense.transaction_date }}</td>
                        <td class="border-black border-r p-2">{{ expense.amount }}</td>
                    </tr>
                {% endfor %}
                <tr class="border-black border-b border-l">
                    <td></td>
                    <td></td>
                    <td class="border-black border-r p-2">{{ sum }} kr</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}